server:
  port: 9001
spring:
  kafka:
    client-id: testclient
    #bootstrap-servers: localhost:9092
    #bootstrap-servers: kafka:9092
    #bootstrap-servers: 172.17.0.1:9092
    #bootstrap-servers: 0.0.0.0:9092
    bootstrap-servers: 192.168.1.195:9092
    consumer:
      group-id: ais-stream-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
---
kafka:
  topic:
    ais-input: ais-input
    ais-output: ais-output
    ais-anamoly: ais-anamoly

logging:
  file: /logs/kafka-ais-stream-consumer.log

model:
  repo-path: AIS_model_3.h5